In [ ]:
import numpy as np
a=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr)
print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr[1:5:4])

[1 2 3 4 5 6 7]
28
4.0
7
[2]


In [19]:
# Plotting functions


import time 
import sys
import numpy as np 

import matplotlib.pyplot as plt


def Plotvec1(u, z, v):
    
    ax = plt.axes() # to generate the full window axes
    ax.arrow(0, 0, *u, head_width=0.05, color='r', head_length=0.1)# Add an arrow to the  U Axes with arrow head width 0.05, color red and arrow head length 0.1
    plt.text(*(u + 0.1), 'u')#Adds the text u to the Axes 
    
    ax.arrow(0, 0, *v, head_width=0.05, color='b', head_length=0.1)# Add an arrow to the  v Axes with arrow head width 0.05, color red and arrow head length 0.1
    plt.text(*(v + 0.1), 'v')#Adds the text v to the Axes 
    
    ax.arrow(0, 0, *z, head_width=0.05, head_length=0.1)
    plt.text(*(z + 0.1), 'z')#Adds the text z to the Axes 
    plt.ylim(-2, 2)#set the ylim to bottom(-2), top(2)
    plt.xlim(-2, 2)#set the xlim to left(-2), right(2)

u = np.array([0, 1])
v = np.array([1, 0])
z = u + v
Plotvec1(u, z, v)


Array Division

In [20]:
a = np.array([10, 20, 30])
b= np.array([1, 2, 3])
c= np.divide(a, b)
print(c)

[10. 10. 10.]


Dot Product

In [29]:
X = np.array([1, 2])
Y = np.array([3, 2])
z= np.dot(X, Y)
print(z)
print(X.size)    

7
2


Mathematical Functions

In [22]:
a=np.pi
print(a)    

3.141592653589793


In [27]:
b=np.e
print(b)  
print(np.exp(1))  
print(np.log(np.e))
print(np.log10(100))
print(np.sqrt(16))
print(np.sin(np.pi/2))      
print(np.cos(0))
print(np.tan(np.pi/4)) 
print(np.arange(0, 10, 2))
print(np.linspace(0, 1, 5))
print(np.random.rand(3))
print(np.random.randn(3))
print(np.random.randint(1, 10, 5))
print(np.zeros((2, 3)))
print(np.ones((2, 3)))

2.718281828459045
2.718281828459045
1.0
2.0
4.0
1.0
1.0
0.9999999999999999
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[0.99930255 0.71774077 0.57297537]
[-0.21350848 -0.12900546 -0.18960804]
[1 2 8 6 5]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [28]:
import time 
import sys
import numpy as np 

import matplotlib.pyplot as plt


def Plotvec2(a,b):
    ax = plt.axes()# to generate the full window axes
    ax.arrow(0, 0, *a, head_width=0.05, color ='r', head_length=0.1)#Add an arrow to the  a Axes with arrow head width 0.05, color red and arrow head length 0.1
    plt.text(*(a + 0.1), 'a')
    ax.arrow(0, 0, *b, head_width=0.05, color ='b', head_length=0.1)#Add an arrow to the  b Axes with arrow head width 0.05, color blue and arrow head length 0.1
    plt.text(*(b + 0.1), 'b')
    plt.ylim(-2, 2)#set the ylim to bottom(-2), top(2)
    plt.xlim(-2, 2)#set the xlim to left(-2), right(2)
a = np.array([1, 1])
b = np.array([2, 0])
Plotvec2(a,b)


In [31]:
X=np.array([[1,0,1],[2,2,2]]) 
print(X)
out=X[0:2,2]
print(out)  

[[1 0 1]
 [2 2 2]]
[1 2]
